### ISSUE TITLE
[Game Recommendation]: <title>

### ISSUE THREAD

**Issue by NYTPlayz** [nate-games/nate-games.github.io#35]
### Rating

10

### Game Name

Papa's Hot Doggeria

### URL of the Game

idk

### Game Type

HTML5

### Comment

you have to search game but go on flipline studios and add all papa's games

**Comment by nate-games** [comment]
will add, just so you the website is no longer going to be updated once it reaches 200 games

SWF: https://www.gameslol.net/data/1731.swf
