### ISSUE TITLE
[Game Recommendation]: <title>

### ISSUE THREAD

**Issue by EcoliEater87** [nate-games/nate-games.github.io#39]
### Rating

8

### Game Name

Tanuki Sunset

### URL of the Game

https://github.com/PurePro4561/Tanuki-Sunset

### Game Type

Don't Know

### Comment

Just wanted to say that your site is quite sophisticated. Good work.

**Comment by nate-games** [comment]
I will add it, seems like a pretty fun game.
Working game URL: https://watchdocumentaries.com/wp-content/uploads/games/tanuki-sunset/
