### ISSUE TITLE
[Link Submission]: <title>

### ISSUE THREAD

**Issue by pr0x1es** [nate-games/nate-games.github.io#45]
### Rating

8.8

### URL

https://dogeminer.airpod1.repl.co/

### Service

Replit

### Comment

You should add it your website the link is to dogeminer and it works for me :)

oh btw i have a website to where i use alot of your games from your github just to let you know im not sure if i need credit

https://sites.google.com/view/p0x/home

thanks!

**Comment by nate-games** [comment]
You don't need credit, I can add the game but next time open it as a game recommendation.

Link submission is if you have a link like 'http://nate-games.com' and your submitting another version of the website.
