### ISSUE TITLE
My favorite game in my opinion

### ISSUE THREAD

**Issue by pr0x1es** [nate-games/nate-games.github.io#46]
### Rating

8.8

### Game Name

Papa's Burgeria

### URL of the Game

https://www.dropbox.com/s/gasqj0ryf363p3i/papasburgeria.swf?dl=0

### Game Type

Flash

### Comment

im not sure if the game file would be fine but im pretty sure WAFLASH or Ruffle supports it.

**Comment by nate-games** [comment]
I'll add the game but I need one favor, resend the doge miner game as a recommendation. 

It keeps me on track of what games to add.
