### ISSUE TITLE
[Bug Reporting]: Error 909 is for SQL databases

### ISSUE THREAD

**Issue by 3kh0** [nate-games/nate-games.github.io#48]
### Page URL

https://github.com/nate-games/nate-games.github.io/wiki/Error-Codes

### Error Type

Other

### Explain

> Code 909
> A common error: specifically for images not loading correctly. Mostly happens, when your school district blocks the website or platform the image is hosted on OR when the image format isn't supported.

In the web, the error code 909 is not possible??

### Sources:
- https://dba.stackexchange.com/questions/128486/error-909-restoring-a-database-on-standard-edition
- https://stackoverflow.com/questions/67921492/sql-error-909-42000-ora-00909-invalid-number-of-arguments

**Comment by nate-games** [comment]
"We use custom error codes and basic errors to easily define the type of error experienced by a user."
