### ISSUE TITLE
[Game Recommendation]: Papa's Pancakeria

### ISSUE THREAD

**Issue by pr0x1es** [nate-games/nate-games.github.io#52]
### Rating

8.9

### Game Name

Papa's Pancakeria

### URL of the Game

https://www.dropbox.com/s/5e7lrgo0h7a0f98/papaspancakeria.swf?dl=0

### Game Type

Flash

### Comment

Pretty S tier game in my opinion

**Comment by nate-games** [comment]
Thanks will come next release!
